services:
  postgres:
    image: postgres:15-alpine
    container_name: niet-ban-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER:-user}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: ${DATABASE_NAME:-niet_ban_os}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - niet-ban-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: niet-ban-redis
    restart: always
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - niet-ban-net

  app:
    build:
      context: .
      target: base
    container_name: niet-ban-app
    command: sh -c "npm install && npx prisma generate && npx prisma db push --accept-data-loss && npx prisma db seed && npm run start:dev"
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://${DATABASE_USER:-user}:${DATABASE_PASSWORD:-password}@postgres:5432/${DATABASE_NAME:-niet_ban_os}?schema=public
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET:-thich-ca-mau-ni}
    volumes:
      - .:/app
      - /app/node_modules # Anonymous volume to protect host modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - niet-ban-net

networks:
  niet-ban-net:
    driver: bridge

volumes:
  postgres_data:
